import pa2checker

insert_ontology_value = pa2checker.insert_ontology_value
update_ontology_utils = pa2checker.update_ontology_utils
recompile_checker_framework = pa2checker.recompile_checker_framework
revert_checker_source = pa2checker.revert_checker_source
